import { NextPage } from "next";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import { MoonLoader } from "react-spinners";

const Home: NextPage = () => {
  const [input, setInput] = useState("");
  const [error, setError] = useState(false);
  const [suggestion, setSuggestion] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (input.length < 30) setError(false);
  }, [input]);

  const submit = async () => {
    if (input.length > 30) return setError(true);

    setLoading(true);
    try {
      const res = await fetch("/api/marketing-copy", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ input }),
      });

      const suggestion: { result: string } = await res.json();
      const { result } = suggestion;
      setSuggestion(result);
    } catch (error) {
      console.log(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Marketing Copy Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl mx-auto py-12">
        <h2 className="text-2xl font-bold text-center pb-2">
          Marketing copy generator
        </h2>
        <div className="flex flex-col gap-4 justify-center w-1/3 mx-auto">
          <div className="relative w-full">
            {error && (
              <p className="text-sm text-red-500 pt-1">
                Character limit exceeded. Please enter less text.
              </p>
            )}
            <textarea
              onChange={(e) => setInput(e.target.value)}
              value={input}
              rows={3}
              className="w-full border-2 border-gray-300 bg-white p-4 rounded-lg text-sm focus:outline-none resize-none"
              placeholder="Enter your topic here"
            />
            <div
              className={`absolute bottom-2 right-2 ${
                input.length > 30 ? "text-red-500" : "text-gray-400"
              } text-xs`}
            >
              <span>{input.length}</span>/30
            </div>
          </div>
          <button
            type="button"
            onClick={submit}
            className="bg-blue-500 h-12 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          >
            {loading ? (
              <div className="flex gap-4 justify-center items-center">
                <p>Loading...</p>
                <MoonLoader size={20} color="white" />
              </div>
            ) : (
              "Generate"
            )}
          </button>

          {suggestion && (
            <div className="mt-8">
              <h4 className="text-lg font-semibold pb-2">
                Your marketing copy:
              </h4>
              <div className="relative w-full rounded-md bg-gray-100 p-4">
                <p className="text-sm text-gray-700">{suggestion}</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
export default Home;
